---
# tasks file for docker
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Downloading install script
  become: true
  get_url:
    url: https://get.docker.com
    dest: /tmp/docker.sh
    mode: 666
    timeout: 10

- name: Executing docker install script
  become: true
  command: bash /tmp/docker.sh

- name: Testing docker installation
  become: true
  command: docker run --rm hello-world

- name: Install docker-compose from official github repo
  become: true
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

# - name: Copying docker-compose directory
#   become: true 
#   copy:
#       src: ../files/
#       dest: /var/docker-compose-files

# - name: Running docker-compose on services to start
#   command: 
#     chdir: "/var/docker-compose-files/{{ item }}"
#     cmd: docker-compose up -d
#   loop: "{{ services }}"